### ISSUE TITLE
minSeverityLevel variable

### ISSUE THREAD

**Issue by mitechniq** [aws-samples/amazon-guardduty-to-slack#1]
Regardless of using Medium or High in the minSeverityLevel variable. I continue to get Severity low notifications in Slack.

**Comment by hadzo** [comment]
Same here, deployed this CloudFormation template to all of my regions and still get Low and Medium Severity notifications on slack all the time even though I've set up minSeverityLevel to HIGH. Any idea why is this happening?

**Comment by philsynek** [comment]
Same here, something is not working correctly...

**Comment by nattig** [comment]
It's not working for me, configured everything, generated sample findings and even have some real findings, still couldn't get any messages in Slack.

**Comment by philsynek** [comment]
I think I found a solution. Still testing, will be back with a commit I guess.

**Comment by golimer** [comment]
can someone merge???

**Comment by wes-novack** [comment]
This issue should be closed now.
