### ISSUE TITLE
Node 8.10 not supported with ZipFile in CloudFormation

### ISSUE THREAD

**Issue by jasonabradley** [aws-samples/amazon-guardduty-to-slack#10]
CloudFormation does not currently support the ZipFile (embedded code) method with Node8.10. Only Node, Node4 and Node6.10.

**Comment by thamizarasu** [comment]
It does support, make sure you are not exceeding the allowed 4096 characters. Maybe you can replace the number of whitespaces used for indentation to save some characters for your changes.

**Comment by wes-novack** [comment]
Code has been updated to `nodejs12.x`. I found no issues deploying this today via the Cloudformation template. Suggest closing this issue.
