### ISSUE TITLE
Question on AWSLambdaVPCAccessExecutionRole

### ISSUE THREAD

**Issue by ahusmc** [aws-samples/amazon-guardduty-to-slack#11]
Is this really necessary or is there a more restrictive permission set that could accomplish the same?

"arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole" It seems to me that GuardDuty doesn't need to do anything with the VPC. It should just receive the guard duty message as JSON and then post it on to slack. Thoughts?

**Comment by ryanholland** [comment]
You are correct that is not needed, I have removed it from the template.
thanks
ryan
