### ISSUE TITLE
Is there any way to test this setup

### ISSUE THREAD

**Issue by akshaykrjain** [aws-samples/amazon-guardduty-to-slack#14]
I have successfully deployed this stack in our test account but before I do the same in prod i would like to perform a test. 

How can I do that?

How to generate fake GuardofDuty alerts or trigger this lambda manually?

**Comment by wes-novack** [comment]
Yes, if you go to GuardDuty settings ( eg; https://us-west-2.console.aws.amazon.com/guardduty/home?region=us-east-1#/settings ) and click the `Generate sample findings` button, it should create a slew of findings in your account, and this Lambda function should alert of the generated events.

This issue should be closed.

**Comment by akshaykrjain** [comment]
Thanks @wes-novack
